# Generated by Django 3.2.5 on 2021-07-11 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemicalName', models.CharField(max_length=100)),
                ('commonName', models.CharField(max_length=100)),
                ('formula', models.CharField(max_length=100)),
                ('molarMass', models.IntegerField()),
                ('acidity', models.CharField(max_length=100)),
                ('polarity', models.CharField(max_length=100)),
                ('solubility', models.CharField(max_length=100)),
            ],
        ),
    ]
