# Generated by Django 3.2.5 on 2021-07-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemical',
            name='molarMass',
            field=models.FloatField(),
        ),
    ]
