# Generated by Django 3.2.5 on 2021-07-12 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_chemical_molarmass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('usedFor', models.CharField(choices=[('Ex', 'Experiment'), ('Co', 'Cooking'), ('Cl', 'Cleaning')], default='Ex', max_length=2)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.chemical')),
            ],
        ),
    ]
