# Generated by Django 3.2.5 on 2021-07-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_utilization_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usecase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ingredients', models.TextField(max_length=300)),
            ],
        ),
    ]
