# Generated by Django 3.2.5 on 2021-07-13 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_usecase'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='usecases',
            field=models.ManyToManyField(to='main_app.Usecase'),
        ),
    ]
